name: 📢 Publish Next

on:
  push:
    branches:
      - main
      - init # TODO: Remove this branch

env:
  NODE_VERSION: 20

jobs:
  publish:
    name: 📢 Publish Next
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      - name: Get Short SHA
        run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
      - name: Get Next Version
        run: |
          current_date=$(date +'%Y%m%d')
          echo "NEW_VERSION=0.0.0-next-${SHORT_SHA}-${current_date}" >> $GITHUB_ENV
      - name: Use Next Version
        run: |
          git config --global user.email "info@descope.com"
          git config --global user.name "Descope"
          yarn version --new-version ${NEW_VERSION}
          cat package.json
      - name: Install dependencies
        run: npm ci
      - name: Build Library
        run: npm run build:ci
      - name: Publish to NPM Package Registry
        run: |
          cd dist
          npm publish --access=public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_REGISTRY }}
